import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  container: {
    padding: 20,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    marginTop: 10,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  divider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 16,
  },
  sectionBlock: {
    marginBottom: 4,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 12,
  },
  pillRow: {
    flexDirection: 'row',
    gap: 8,
  },
  pill: {
    paddingVertical: 7,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  pillActive: {
    backgroundColor: '#1A1A2E',
    borderColor: '#1A1A2E',
  },
  pillText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6B7280',
  },
  pillTextActive: {
    color: '#FFFFFF',
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#BFDBFE',
    gap: 12,
  },
  infoUnit: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1D4ED8',
    minWidth: 32,
    textAlign: 'center',
  },
  infoDesc: {
    flex: 1,
    fontSize: 13,
    color: '#3B82F6',
    fontWeight: '500',
  },
  generateBtn: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    marginBottom: 16,
  },
  generateBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  chartHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 0,
  },
  emptyBadge: {
    backgroundColor: '#FEF3C7',
    borderRadius: 10,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#FDE68A',
    marginBottom: 12,
  },
  emptyBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#D97706',
  },
  hintBox: {
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
  },
  hintText: {
    fontSize: 13,
    color: '#9CA3AF',
    lineHeight: 19,
    textAlign: 'center',
  },
  hintBold: {
    color: '#007AFF',
    fontWeight: '700',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  statValueSkeleton: {
    width: 40,
    height: 20,
    borderRadius: 6,
    backgroundColor: '#E5E7EB',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  allTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  allTimeItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 4,
  },
  allTimeDivider: {
    width: 1,
    height: 36,
    backgroundColor: '#E5E7EB',
  },
  allTimeLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  allTimeValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A2E',
  },
});

export const skeletonStyles = StyleSheet.create({
  chartArea: {
    flexDirection: 'row',
    height: 180,
    marginBottom: 10,
  },
  yAxis: {
    width: 28,
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingRight: 6,
    paddingVertical: 4,
  },
  skeletonYLabel: {
    width: 20,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
  chartBody: {
    flex: 1,
    paddingVertical: 4,
  },
  barsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    flex: 1,
    gap: 6,
  },
  barWrapper: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
  },
  skeletonBar: {
    borderRadius: 6,
    backgroundColor: '#E5E7EB',
    width: '100%',
  },
  xAxisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 34,
  },
  skeletonXLabel: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
});
